default: &default
  # marketplace_password_salt: <%= ENV['MARKETPLACE_PASSWORD_SALT'] %>

development:
  <<: *default
  secret_key_base:  development_secret_key_base

test:
  secret_key_base: test_secret_key_base
  <<: *default

production:
  secret_key_base: <%= ENV['MARKETPLACE_SECRET_KEY_BASE'] %>
  <<: *default
