default: &default 
  # marketplace_password_salt: <%= ENV['MARKETPLACE_PASSWORD_SALT'] %> # Used for JWT encryption
  secret_key_base: <%= ENV['MARKETPLACE_SECRET_KEY_BASE'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
